"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

type Language = "en" | "zh"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<string, Record<Language, string>> = {
  // ===== Sidebar Navigation =====
  "nav.home": { en: "Home", zh: "首页" },
  "nav.agenticCatalog": { en: "Agentic Catalog", zh: "Agent原生商品" },
  "nav.yourProducts": { en: "Your Products", zh: "您的商品" },
  "nav.connectShop": { en: "Connect Shop", zh: "连接店铺" },
  "nav.connectFeed": { en: "Connect Feed", zh: "连接Feed" },
  "nav.manualUpload": { en: "Manual Upload", zh: "手动上传" },
  "nav.discover": { en: "Discover", zh: "发现" },
  "nav.products": { en: "Products", zh: "商品" },
  "nav.brands": { en: "Brands", zh: "品牌" },
  "nav.websites": { en: "Websites", zh: "网站" },
  "nav.categories": { en: "Categories", zh: "品类" },
  "nav.brandContext": { en: "Brand Context", zh: "品牌信息" },
  "nav.details": { en: "Details", zh: "详情" },
  "nav.guardrails": { en: "Guardrails", zh: "品牌护栏" },
  "nav.visualStyle": { en: "Visual Style", zh: "视觉风格" },
  "nav.brandStory": { en: "Brand Story", zh: "品牌故事" },
  "nav.postsUgc": { en: "Posts & UGC Assets", zh: "帖子与UGC素材" },
  "nav.fulfillment": { en: "Fulfillment", zh: "履约配送" },
  "nav.channelControl": { en: "Channel", zh: "Agent渠道控制" },
  "nav.conversationalStorefront": { en: "Conversational Storefront", zh: "对话式店面" },
  "nav.thirdPartyAgents": { en: "Third Party Agents", zh: "第三方智能体" },
  "nav.creatorAgents": { en: "Creator Agents", zh: "创作者智能体" },
  "nav.analytics": { en: "Analytics", zh: "数据分析" },
  "nav.seller": { en: "Seller", zh: "商家" },
  
  // ===== Home Page =====
  "home.totalRevenue": { en: "Total Revenue", zh: "总收入" },
  "home.orders": { en: "Orders", zh: "订单数" },
  "home.conversionRate": { en: "Conversion Rate", zh: "转化率" },
  "home.avgOrderValue": { en: "Avg Order Value", zh: "客单价" },
  "home.vsLastMonth": { en: "vs last month", zh: "较上月" },
  "home.pro": { en: "PRO", zh: "PRO" },
  "home.buildAgentNative": { en: "Build Agent-native Products with Nohi Central Pro", zh: "使用 Nohi Central Pro 构建Agent原生商品货架" },
  "home.integrate130": { en: "Integrate with 130+ Nohi-only entrances", zh: "接入130+个Nohi专属入口" },
  "home.buildBrandOwned": { en: "Build brand-owned agent clusters", zh: "构建品牌自有智能体集群" },
  "home.automatedListing": { en: "Automated product listing", zh: "自动化商品上架" },
  "home.instantCheckout": { en: "Instant checkout on every product card", zh: "每张商品卡片即时结算" },
  "home.requestForPro": { en: "Request for Pro", zh: "申请Pro" },
  "home.requestSent": { en: "Request sent", zh: "已提交申请" },
  "home.proDisclaimer": { en: "You must be invited or selected to use Nohi Central Pro. Prove your success with the current version first.", zh: "您需要被邀请或选中才能使用 Nohi Central Pro。请先用当前版本证明您的成功。" },
  "home.aboutNohi": { en: "About Nohi", zh: "关于 Nohi" },
  "home.learnMore": { en: "Learn more about the Nohi platform and how to maximize your agentic commerce presence.", zh: "了解更多关于Nohi平台以及如何最大化您的智能体商务影响力。" },
  "home.gettingStarted": { en: "Getting Started Guide", zh: "快速入门指南" },
  "home.bestPractices": { en: "Best Practices", zh: "最佳实践" },
  "home.apiDocs": { en: "API Documentation", zh: "API文档" },
  "home.helpCenter": { en: "Help Center", zh: "帮助中心" },
  "home.channelDocs": { en: "Channel Documentation", zh: "渠道文档" },
  "home.channelDocsDesc": { en: "Learn about each distribution channel and how to optimize your presence.", zh: "了解每个分发渠道以及如何优化您的曝光。" },
  "home.onboardingTitle": { en: "Complete your setup", zh: "完成入门设置" },
  "home.onboardingDesc": { en: "Complete these tasks to launch your first campaign and unlock ad credits.", zh: "完成以下任务，即可启动首个广告活动并解锁广告积分。" },
  "home.onboardingGoTo": { en: "Go to Getting Started", zh: "前往快速开始" },
  "home.onboardingDone": { en: "tasks done", zh: "项已完成" },
  
  // ===== Settings Page =====
  "settings.title": { en: "Store Settings", zh: "店铺设置" },
  "settings.description": { en: "Manage your store information and preferences.", zh: "管理您的店铺信息和偏好设置。" },
  "settings.language": { en: "Language", zh: "语言" },
  "settings.languageDesc": { en: "Choose your preferred language for the Nohi Seller Central interface.", zh: "选择Nohi商家中心界面的显示语言。" },
  "settings.languageNote": { en: "The interface will switch to Simplified Chinese. Some content may still appear in English.", zh: "界面将切换为简体中文显示。部分内容可能仍以英文显示。" },
  "settings.storeInfo": { en: "Store Information", zh: "店铺信息" },
  "settings.brandName": { en: "Brand name", zh: "品牌名称" },
  "settings.storeLink": { en: "Store link", zh: "店铺链接" },
  "settings.category": { en: "Category", zh: "类目" },
  "settings.gmvRange": { en: "Yearly GMV range", zh: "年GMV范围" },
  "settings.teamSize": { en: "Team size", zh: "团队规模" },
  "settings.cancel": { en: "Cancel", zh: "取消" },
  "settings.saveChanges": { en: "Save changes", zh: "保存更改" },
  "settings.saving": { en: "Saving...", zh: "保存中..." },
  "settings.paymentMethods": { en: "Payment Methods", zh: "支付方式" },
  "settings.addPaymentMethod": { en: "Add Payment Method", zh: "添加支付方式" },
  "settings.default": { en: "Default", zh: "默认" },
  "settings.setAsDefault": { en: "Set as default", zh: "设为默认" },
  "settings.endingIn": { en: "ending in", zh: "尾号" },
  "settings.cardNumber": { en: "Card number", zh: "卡号" },
  "settings.expiryDate": { en: "Expiry date", zh: "有效期" },
  "settings.addCard": { en: "Add Card", zh: "添加卡片" },
  "settings.buyTokens": { en: "Buy Extra Tokens", zh: "购买额外令牌" },
  "settings.tokensDesc": { en: "Tokens are used for AI agent interactions and product placements.", zh: "令牌用于AI智能体交互和商品展示。" },
  "settings.learnTokens": { en: "Learn more about tokens", zh: "了解更多令牌信息" },
  "settings.currentBalance": { en: "Current balance", zh: "当前余额" },
  "settings.tokens": { en: "tokens", zh: "令牌" },
  "settings.popular": { en: "Popular", zh: "热门" },
  "settings.purchase": { en: "Purchase", zh: "购买" },
  "settings.selectPlan": { en: "Select a plan", zh: "选择套餐" },
  "settings.additionalInfo": { en: "This information helps us match you with the right AI shoppers and optimize your store's performance on Nohi marketplace.", zh: "这些信息帮助我们为您匹配合适的AI购物者，并优化您在Nohi市场的店铺表现。" },

  // ===== Onboarding =====
  "onboarding.section": { en: "Getting started", zh: "快速开始" },
  "onboarding.hello": { en: "Hello, User", zh: "你好，用户" },
  "onboarding.completeTitle": { en: "Complete onboarding", zh: "完成入门设置" },
  "onboarding.completeDesc": { en: "Complete these tasks in any order to launch your first campaign.", zh: "按任意顺序完成以下任务，即可启动您的首个广告活动。" },
  "onboarding.tasksCompleted": { en: "tasks completed", zh: "项任务已完成" },
  "onboarding.creditBanner": { en: "Create your first campaign to qualify for up to", zh: "创建您的首个广告活动，即可获得最高" },
  "onboarding.creditBannerSuffix": { en: "in ad credit.", zh: "的广告积分。" },
  "onboarding.learnMore": { en: "Learn more", zh: "了解更多" },
  "onboarding.task": { en: "Task", zh: "任务" },
  "onboarding.aiAssisted": { en: "AI-assisted", zh: "AI辅助" },
  "onboarding.done": { en: "Done", zh: "已完成" },
  "onboarding.todo": { en: "To do", zh: "待完成" },
  "onboarding.viewSetup": { en: "View setup", zh: "查看设置" },
  "onboarding.setUp": { en: "Set up", zh: "立即设置" },
  "onboarding.createCampaign": { en: "Create campaign", zh: "创建广告活动" },
  "onboarding.paymentTitle": { en: "Set up payment", zh: "设置支付方式" },
  "onboarding.paymentDesc": { en: "Set up payment method and review your billing address to enable transactions.", zh: "设置支付方式并确认账单地址，以启用交易功能。" },
  "onboarding.feedTitle": { en: "Set up Nohi Agentic Catalog", zh: "设置 Nohi Agentic 目录" },
  "onboarding.feedDesc": { en: "Connect your product catalog to Nohi's Agentic Catalog to make your products discoverable by AI agents.", zh: "将您的产品目录连接至 Nohi Agentic 目录，让 AI 智能体能够发现您的商品。" },
  "onboarding.eventsTitle": { en: "Set up events", zh: "设置事件追踪" },
  "onboarding.eventsDesc": { en: "Implement key events to monitor shopper behavior and refine your marketing strategies.", zh: "部署关键事件以监测购物行为，优化您的营销策略。" },
  "onboarding.eventsDialogTitle": { en: "Set up events", zh: "设置事件追踪" },
  "onboarding.eventsDialogBody1": { en: "Events track a user action (views, add-to-cart, purchases, and more) to enhance targeting and monitoring. Once your events are configured, Nohi will analyze your event data to provide campaign-boosting insights.", zh: "事件追踪用于记录用户行为（浏览、加入购物车、购买等），提升广告定向精度与监测能力。事件配置完成后，Nohi 将分析数据以提供优化广告活动的洞察。" },
  "onboarding.eventsDialogBody2": { en: "You can connect your shop or select another method (Google Tag Manager or manual setup). After setup, test your events to make sure they're working as expected.", zh: "您可以连接店铺，或选择其他方式（Google Tag Manager 或手动配置）。设置完成后，请测试事件以确保正常运行。" },
  "onboarding.shopDetected": { en: "Shop detected", zh: "检测到店铺" },
  "onboarding.shopDetectedDesc": { en: "Connect your shop account to Nohi to set up your events in a few clicks. Or select another setup method (Google Tag Manager or manual).", zh: "将您的店铺账号连接至 Nohi，仅需几步即可完成事件设置。也可选择其他方式（Google Tag Manager 或手动配置）。" },
  "onboarding.selectAnotherMethod": { en: "Select another method", zh: "选择其他方式" },
  "onboarding.connectShop": { en: "Connect Shop", zh: "连接店铺" },
  "onboarding.termsOfSale": { en: "Terms of sale", zh: "销售条款" },
  "onboarding.privacyPolicy": { en: "Privacy policy", zh: "隐私政策" },
  "onboarding.contact": { en: "Contact", zh: "联系我们" },

  // ===== Promotional Credits FAQ =====
  "faq.title": { en: "Promotional credit FAQ", zh: "推广积分常见问题" },
  "faq.back": { en: "Billing and payments", zh: "账单与付款" },
  "faq.breadcrumb": { en: "Billing and payments › Promotional credit FAQ", zh: "账单与付款 › 推广积分常见问题" },
  "faq.q1": { en: "What are promotional credits?", zh: "什么是推广积分？" },
  "faq.a1": { en: "Promotional credits are free dollar-for-dollar credits that match your spending on your first campaign. When you set a qualifying budget and meet the spending threshold within 30 days, an equal amount of credits is awarded. These credits can be used to cover future campaign costs within a set period, subject to usage limits, vesting rules, and expiration dates. They are available in multiple currencies and are applied automatically once earned.", zh: "推广积分是与您首次广告活动消费额等额的免费积分。当您设定符合条件的预算并在30天内达到消费门槛时，将获得等额积分。这些积分可在设定期限内用于抵扣未来的广告费用，受使用限额、归属规则及到期日期约束，支持多种货币，达标后自动发放。" },
  "faq.q2": { en: "What are the conditions for me to be eligible for promotional credits?", zh: "获得推广积分需要满足哪些条件？" },
  "faq.a2": { en: "You must be a first-time advertiser creating your first account or campaign. A promotional voucher is created for your first campaign once you meet the spending threshold.\n\nNew advertisers must launch their first campaign within 30 days of account creation to benefit from the promotional credits.\n\nThe qualification period starts from your campaign's start date, even if the campaign is scheduled for the future. The voucher is activated when the required spend is reached.\n\nOnly one voucher can be active per advertiser, and the offer always applies as it was defined at the time of voucher creation, not if thresholds or ratios change later.", zh: "您必须是首次注册广告账户或创建广告活动的新广告主。首次广告活动达到消费门槛后，系统将自动创建推广凭证。\n\n新广告主需在账户创建后30天内启动首个广告活动，方可享受推广积分。\n\n资格认定期从广告活动开始日期起算，即使活动为预计日期。达到所需消费额后凭证即激活。\n\n每位广告主同一时间只能有一个有效凭证，优惠条款以凭证创建时的规则为准，后续门槛或比例调整不影响已创建凭证。" },
  "faq.q3": { en: "How are promotional credits calculated?", zh: "推广积分如何计算？" },
  "faq.a3": { en: "Promotional credits are matched dollar-for-dollar based on your spending. When you set a budget of at least $400 (up to $1,200), a promotional voucher is activated. Whatever amount you spend within 30 days is matched with an equal amount in free credits.\n\nOnce obtained, the ad credits can be used to cover future charges for up to 60 days, subject to vesting limits. Unused credits expire after this period.", zh: "推广积分按您的实际消费额等额匹配。当您设定至少 $400（最高 $1,200）的预算时，推广凭证激活。30天内的消费额将被等额匹配为免费积分。\n\n获得积分后，可在60天内用于抵扣未来费用，受归属限额约束，未使用积分将在此期限后过期。" },
  "faq.q4": { en: "What is the timeline for earning and using promotional credits?", zh: "推广积分的获取和使用时间线是什么？" },
  "faq.a4": { en: "You earn promotional credits based on your spend during the first 30 days after your campaign starts. The matched free credits become available once the required spend is reached.\n\nAfter the credits are obtained, you have 60 days to spend them before they expire, subject to monthly usage limits.", zh: "广告活动启动后的前30天内，根据您的消费额获取推广积分。达到所需消费额后，等额免费积分即可使用。\n\n获得积分后，您有60天时间使用，受每月使用限额约束，过期后积分作废。" },
  "faq.q5": { en: "Who is eligible, and how much credit can I receive?", zh: "谁有资格获得积分，最多可获得多少？" },
  "faq.a5": { en: "To qualify, you must spend at least $400 within 30 days of your campaign start. Eligible customers can receive dollar-for-dollar promotional credits up to a maximum of $1,200. Once earned, free credits can be used for up to 60 days.", zh: "如需获得资格，需在广告活动启动后30天内消费至少 $400。符合条件的用户可获得最高 $1,200 的等额推广积分，积分有效期60天。" },
  "faq.q6": { en: "How does promotional credit vesting work?", zh: "推广积分的归属规则是什么？" },
  "faq.a6": { en: "Promotional credits are subject to a monthly usage limit tied to your actual spend. You can use free credits to cover up to 70% of your campaign spend during the next campaign period.\n\nFor example, if you spend $1,000 during the next period, you can use up to $700 in promotional credits during that period. The remaining 30% of your earned credits can be used during the third month, as long as the voucher has not expired.", zh: "推广积分受与实际消费挂钩的每月使用限额约束。在下一个广告周期内，您可用免费积分抵扣最多70%的广告消费。\n\n例如，若下一周期消费 $1,000，则可使用最多 $700 的推广积分。剩余30%的积分可在第三个月使用，前提是凭证未过期。" },
  "faq.q7": { en: "Which currencies are supported for promotional credits?", zh: "推广积分支持哪些货币？" },
  "faq.a7": { en: "Promotional credits are matched using predefined minimum and maximum amounts in EUR, USD, and GBP. For other currencies, credit amounts are calculated using a conversion from USD based on current exchange rates.", zh: "推广积分以EUR、USD和GBP的预设最低和最高金额进行匹配。其他货币的积分金额按当前汇率从USD换算得出。" },
  "faq.tableColCurrency": { en: "Currency", zh: "货币" },
  "faq.tableColMin": { en: "Minimum threshold", zh: "最低消费门槛" },
  "faq.tableColMax": { en: "Maximum credit", zh: "最高积分上限" },
  "faq.q8": { en: "How are promotional credits applied to my bill?", zh: "推广积分如何抵扣账单？" },
  "faq.a8": { en: "Promotional credits are applied automatically to your account. There is no code to enter and no manual redemption process required. When promotional credits are used, they appear as a discount line on your usual bill, reducing the total amount charged for eligible campaign spend.", zh: "推广积分自动应用至您的账户，无需输入代码或手动兑换。使用推广积分时，账单中将显示为折扣行，减少符合条件的广告消费应付金额。" },

  // ===== Product Catalog =====
  "productCatalog.title": { en: "Nohi Agentic Catalog", zh: "Nohi Agentic 目录" },
  "productCatalog.desc": { en: "Import and manage all products displayed in your campaigns.", zh: "导入并管理广告活动中展示的所有商品。" },
  "productCatalog.breadcrumb": { en: "Nohi Agentic Catalog", zh: "Nohi Agentic 目录" },
  "productCatalog.tabOverview": { en: "Overview", zh: "概览" },
  "productCatalog.tabProducts": { en: "Products", zh: "商品" },
  "productCatalog.tabFeeds": { en: "Feeds", zh: "Feed" },
  // Overview
  "productCatalog.yourDashboard": { en: "Your dashboard", zh: "您的仪表盘" },
  "productCatalog.actionNeeded": { en: "Action needed", zh: "需要操作" },
  "productCatalog.actionNeededDesc": { en: "Review your warnings and issues.", zh: "查看您的警告和问题。" },
  "productCatalog.noIssues": { en: "Looking good! You have no warnings or issues to review.", zh: "一切正常！您没有需要查看的警告或问题。" },
  "productCatalog.feedStatus": { en: "Feed status", zh: "Feed 状态" },
  "productCatalog.feedStatusDesc": { en: "See how well your scheduled imports go.", zh: "查看您的定时导入执行情况。" },
  "productCatalog.noScheduledImport": { en: "You haven't scheduled any import yet.", zh: "您尚未安排任何导入计划。" },
  "productCatalog.goToFeeds": { en: "Go to feeds", zh: "前往 Feeds" },
  "productCatalog.performanceInsights": { en: "Performance insights", zh: "性能洞察" },
  "productCatalog.insightTip": { en: "Provide the correct Google category to improve product discoverability and performance", zh: "提供正确的 Google 分类以提升产品可发现性和性能" },
  "productCatalog.downloadReport": { en: "Download report", zh: "下载报告" },
  "productCatalog.seeAll": { en: "See all", zh: "查看全部" },
  "productCatalog.manualFeedBanner": { en: "Looking for manual feed imports? Test your connection and import your feed in Feeds > Feed Settings.", zh: "需要手动导入 Feed？请在 Feeds > Feed 设置 中测试连接并导入。" },
  "productCatalog.learnMore": { en: "Learn more", zh: "了解更多" },
  "productCatalog.latestUpdates": { en: "Get the latest updates on your catalog", zh: "获取目录最新动态" },
  "productCatalog.globalStats": { en: "Global product stats", zh: "全局商品统计" },
  "productCatalog.productsDetails": { en: "Products details", zh: "商品详情" },
  "productCatalog.matchRate": { en: "Catalog and events match rate", zh: "目录与事件匹配率" },
  "productCatalog.globalStatsDesc": { en: "Overview of your total imported products and their status.", zh: "已导入商品总数及其状态概览。" },
  "productCatalog.productsDetailsDesc": { en: "Breakdown of product fields, quality and issues.", zh: "商品字段、质量及问题细项。" },
  "productCatalog.matchRateDesc": { en: "See how well your events match products in your catalog.", zh: "查看您的事件与目录商品的匹配程度。" },
  // Products tab
  "productCatalog.displayable": { en: "Displayable products", zh: "可展示商品" },
  "productCatalog.blocked": { en: "Blocked products", zh: "已屏蔽商品" },
  "productCatalog.unblockReq": { en: "Unblock requests", zh: "解除屏蔽申请" },
  "productCatalog.listOfLive": { en: "List of live products", zh: "在线商品列表" },
  "productCatalog.listDesc": { en: "A list of random selection of up to 500 of your live products.", zh: "随机展示最多 500 件在线商品。" },
  "productCatalog.searchPlaceholder": { en: "Search multiple product IDs separated by a comma", zh: "输入多个商品 ID，用逗号分隔" },
  "productCatalog.hideProducts": { en: "Hide products", zh: "隐藏商品" },
  "productCatalog.exportDetails": { en: "Export product details", zh: "导出商品详情" },
  "productCatalog.seeProductDetails": { en: "See product details", zh: "查看商品详情" },
  "productCatalog.colImage": { en: "Image", zh: "图片" },
  "productCatalog.colProductId": { en: "Product Identification", zh: "商品标识" },
  "productCatalog.colDisplayable": { en: "Displayable", zh: "可展示" },
  "productCatalog.colDescription": { en: "Description", zh: "描述" },
  "productCatalog.colProductUrl": { en: "Product URL", zh: "商品链接" },
  "productCatalog.colPrice": { en: "Price", zh: "价格" },
  "productCatalog.colRetailPrice": { en: "Retail price", zh: "零售价" },
  "productCatalog.colBrand": { en: "Brand", zh: "品牌" },
  "productCatalog.colStock": { en: "Stock", zh: "库存" },
  // Feeds tab
  "productCatalog.colFeedId": { en: "Feed ID", zh: "Feed ID" },
  "productCatalog.colFeedName": { en: "Feed name", zh: "Feed 名称" },
  "productCatalog.colFeedUrl": { en: "Feed URL", zh: "Feed URL" },
  "productCatalog.colStability": { en: "Feed stability", zh: "Feed 稳定性" },
  "productCatalog.colAutoImport": { en: "Auto import", zh: "自动导入" },
  "productCatalog.colSchedule": { en: "Import schedule", zh: "导入计划" },
  "productCatalog.colLinkedFeed": { en: "Linked feed", zh: "关联 Feed" },
  "productCatalog.colLastStatus": { en: "Last import status", zh: "上次导入状态" },
  "productCatalog.colActions": { en: "Actions", zh: "操作" },
  "productCatalog.statusOn": { en: "On", zh: "开启" },
  "productCatalog.statusOff": { en: "Off", zh: "关闭" },
  "productCatalog.statusSuccess": { en: "Success", zh: "成功" },
  "productCatalog.onboardingBanner": { en: "To unlock the full potential of your campaigns, don't forget to complete the onboarding process.", zh: "为充分发挥广告活动潜力，请记得完成入门设置。" },
  "productCatalog.goToOnboarding": { en: "Go to Onboarding", zh: "前往入门设置" },

  // ===== Channel Control =====
  "channel.active": { en: "Active", zh: "已启用" },
  "channel.inactive": { en: "Inactive", zh: "已禁用" },
  "channel.organic": { en: "Organic", zh: "自然流量" },
  "channel.paid": { en: "Paid", zh: "付费" },
  "channel.alwaysOn": { en: "Always On", zh: "始终开启" },
  "channel.pro": { en: "Pro", zh: "Pro" },
  "channel.disconnected": { en: "Disconnected", zh: "未连接" },
  "channel.status": { en: "Channel Status", zh: "渠道状态" },
  "channel.enabled": { en: "Enabled", zh: "已启用" },
  "channel.disabled": { en: "Disabled", zh: "已禁用" },
  "channel.enableDisable": { en: "Enable or disable the conversational storefront for your site.", zh: "启用或禁用您网站的对话式店面。" },
  "channel.alwaysOnDesc": { en: "This channel is always enabled to ensure maximum reach.", zh: "此渠道始终启用以确保最大覆盖范围。" },
  "channel.disableWarningTitle": { en: "Disable Conversational Storefront?", zh: "禁用对话式店面？" },
  "channel.disableWarningDesc": { en: "Disabling your conversational storefront will significantly impact your product card generation quality in agentic channels. Your products may receive lower visibility and conversion rates across AI-powered shopping experiences.", zh: "禁用对话式店面将显著影响您在智能体渠道中的产品卡片生成质量。您的产品在AI驱动的购物体验中可能获得较低的曝光和转化率。" },
  "channel.keepEnabled": { en: "Keep Enabled", zh: "保持启用" },
  "channel.disableAnyway": { en: "Disable Anyway", zh: "仍然禁用" },
  "channel.activationNote": { en: "*We need your conversational storefront to be activated to effectively generate product cards with high conversion in agentic channels.", zh: "*我们需要您激活对话式店面，才能在智能体渠道中有效生成高转化率的产品卡片。" },
  "channel.comingSoon": { en: "Channel Coming Soon", zh: "渠道即将推出" },
  "channel.comingSoonDesc": { en: "This channel integration is not yet available. Check back later for updates.", zh: "此渠道集成尚未可用。请稍后查看更新。" },
  "channel.connectAgenticCatalog": { en: "Connect with Nohi Agentic Catalog", zh: "连接至 Nohi Agentic 目录" },
  "channel.connectAgenticCatalogDesc": { en: "When enabled, your products will be distributed on this channel via the Nohi Agentic Catalog.", zh: "启用后，您的产品将通过 Nohi Agentic 目录在此渠道中分发。" },
  "channel.connectAgenticCatalogHint": { en: "Once enabled, Nohi will automatically sync your product catalog to this channel. Make sure your Agentic Catalog is set up first.", zh: "开启后，Nohi 将自动将您的产品目录同步至此渠道。请确保您的 Agentic 目录已完成设置。" },
  "channel.channelStatus": { en: "Channel Status", zh: "渠道状态" },
  "channel.enableDisableChannel": { en: "Enable or disable this channel for your store.", zh: "为您的店铺启用或禁用此渠道。" },
  "channel.configureChannel": { en: "Configure this channel for your store.", zh: "为您的店铺配置此渠道。" },
  "channel.features": { en: "Features", zh: "功能" },
  "channel.channelAnalytics": { en: "Channel Analytics", zh: "渠道分析" },
  "channel.performanceMetrics": { en: "Performance metrics for this channel.", zh: "此渠道的性能指标。" },
  "channel.views": { en: "Views", zh: "浏览量" },
  "channel.orders": { en: "Orders", zh: "订单数" },
  "channel.revenue": { en: "Revenue", zh: "收入" },
  "channel.saveChanges": { en: "Save Changes", zh: "保存更改" },
  "channel.viewDocs": { en: "View Documentation", zh: "查看文档" },
  "channel.appSelection": { en: "App Selection", zh: "应用选择" },
  "channel.appSelectionDesc": { en: "Choose which ChatGPT App to integrate with. App detection required.", zh: "选择要集成的ChatGPT应用。需要应用检测。" },
  "channel.customApp": { en: "Custom ChatGPT App", zh: "自定义ChatGPT应用" },
  "channel.customAppDesc": { en: "Connect your own custom GPT app", zh: "连接您自己的自定义GPT应用" },
  "channel.nohiApp": { en: "Nohi ChatGPT App", zh: "Nohi ChatGPT应用" },
  "channel.nohiAppDesc": { en: "Use Nohi's official ChatGPT integration", zh: "使用Nohi官方ChatGPT集成" },
  "channel.enableIntegration": { en: "Enable ChatGPT App integration for your store.", zh: "为您的店铺启用ChatGPT应用集成。" },
  
  // Conversational Storefront
  "storefront.title": { en: "Conversational Storefront", zh: "对话式店面" },
  "storefront.description": { en: "Configure how AI shopping assistants interact with your customers on your storefront.", zh: "配置AI购物助手如何在您的店面上与客户互动。" },
  "storefront.layoutVersion": { en: "Layout Version", zh: "布局版本" },
  "storefront.layoutDesc": { en: "Choose how the chat interface appears on your storefront.", zh: "选择聊天界面在店面上的展示方式。" },
  "storefront.splitScreen": { en: "Split Screen", zh: "分屏布局" },
  "storefront.splitScreenDesc": { en: "Chat panel on the side with products in main area", zh: "聊天面板在侧边，商品在主区域" },
  "storefront.inlineChat": { en: "Inline Chat", zh: "内嵌聊天" },
  "storefront.inlineChatDesc": { en: "Floating chat input at the bottom of the page", zh: "页面底部悬浮聊天输入框" },
  "storefront.entryPoints": { en: "Entry Points", zh: "入口点" },
  "storefront.entryPointsDesc": { en: "Select how customers can start a conversation.", zh: "选择客户开始对话的方式。" },
  "storefront.searchAiMode": { en: "Search AI Mode", zh: "搜索AI模式" },
  "storefront.searchAiModeDesc": { en: "AI mode toggle in search bar", zh: "搜索栏中的AI模式切换" },
  "storefront.chatBox": { en: "Chat Box", zh: "聊天框" },
  "storefront.chatBoxDesc": { en: "Persistent chat input at page bottom", zh: "页面底部固定聊天输入框" },
  "storefront.floatingBubble": { en: "Floating Bubble", zh: "悬浮气泡" },
  "storefront.floatingBubbleDesc": { en: "Chat bubble in corner of page", zh: "页面角落的聊天气泡" },
  "storefront.scenarioQueries": { en: "Default Scenario Queries", zh: "默认场景问题" },
  "storefront.scenarioQueriesDesc": { en: "Suggested questions to help customers start a conversation.", zh: "帮助客户开始对话的建议问题。" },
  "storefront.addQuery": { en: "Add a scenario query...", zh: "添加场景问题..." },
  "storefront.cardTheme": { en: "Product Card Theme", zh: "产品卡片主题" },
  "storefront.cardThemeDesc": { en: "Choose how product cards appear in conversations.", zh: "选择产品卡片在对话中的展示方式。" },
  "storefront.minimal": { en: "Minimal", zh: "简约" },
  "storefront.minimalDesc": { en: "Clean, simple cards", zh: "简洁明了的卡片" },
  "storefront.detailed": { en: "Detailed", zh: "详细" },
  "storefront.detailedDesc": { en: "Full product info", zh: "完整产品信息" },
  "storefront.visual": { en: "Visual", zh: "视觉" },
  "storefront.visualDesc": { en: "Image-focused cards", zh: "以图片为主的卡片" },
  "storefront.compact": { en: "Compact", zh: "紧凑" },
  "storefront.compactDesc": { en: "Small, grid-friendly", zh: "小巧适合网格布局" },
  "storefront.sellNonOwned": { en: "Sell Non-Owned Products", zh: "销售非自有产品" },
  "storefront.sellNonOwnedDesc": { en: "Allow the AI to recommend and sell products from the Nohi database that you don't own.", zh: "允许AI推荐和销售Nohi数据库中您不拥有的产品。" },
  "storefront.watchDemo": { en: "Watch Demo Video", zh: "观看演示视频" },

  // ===== Catalog =====
  "catalog.ownSupply": { en: "Own Supply", zh: "自有供应" },
  "catalog.yourProducts": { en: "Your Products", zh: "您的商品" },
  "catalog.yourProductsDesc": { en: "Import your own product catalog via CSV upload.", zh: "通过CSV上传导入您的产品目录。" },
  "catalog.importFromCsv": { en: "Import from CSV", zh: "从CSV导入" },
  "catalog.importFromCsvDesc": { en: "Import products from a CSV or TXT file. Map columns to product fields and update existing products.", zh: "从CSV或TXT文件导入产品。将列映射到产品字段并更新现有产品。" },
  "catalog.importProducts": { en: "Import Products", zh: "导入商品" },
  "catalog.csvTemplate": { en: "CSV Template", zh: "CSV模板" },
  "catalog.csvTemplateDesc": { en: "Download our CSV template to ensure your product data is formatted correctly for import.", zh: "下载我们的CSV模板，确保您的产品数据格式正确以便导入。" },
  "catalog.downloadTemplate": { en: "Download Template", zh: "下载模板" },
  "catalog.productsInCatalog": { en: "Products in Catalog", zh: "目录中的商品" },
  "catalog.importToStart": { en: "Import products to get started", zh: "导入商品以开始" },
  "catalog.connectors": { en: "Connectors", zh: "平台连接器" },
  "catalog.connectorsDesc": { en: "Connect your existing e-commerce platforms to sync products automatically.", zh: "连接您现有的电商平台以自动同步商品。" },
  "catalog.connected": { en: "Connected", zh: "已连接" },
  "catalog.connect": { en: "Connect", zh: "连接" },
  "catalog.productsImported": { en: "products imported", zh: "个商品已导入" },

  // CSV Import
  "import.title": { en: "Import Products", zh: "导入商品" },
  "import.step1": { en: "Upload CSV file", zh: "上传CSV文件" },
  "import.step2": { en: "Column mapping", zh: "字段映射" },
  "import.step3": { en: "Import", zh: "导入" },
  "import.step4": { en: "Done!", zh: "完成！" },
  "import.uploadTitle": { en: "Import products from a CSV file", zh: "从CSV文件导入商品" },
  "import.uploadDesc": { en: "This tool allows you to import (or merge) product data to your store from a CSV or TXT file.", zh: "此工具允许您从CSV或TXT文件导入（或合并）产品数据到您的店铺。" },
  "import.chooseFile": { en: "Choose a CSV file from your computer:", zh: "从您的电脑选择CSV文件：" },
  "import.chooseFileBtn": { en: "Choose File", zh: "选择文件" },
  "import.noFileChosen": { en: "No file chosen", zh: "未选择文件" },
  "import.maxSize": { en: "Maximum size: 2 GB", zh: "最大大小：2 GB" },
  "import.updateExisting": { en: "Update existing products", zh: "更新现有产品" },
  "import.updateExistingDesc": { en: "Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped.", zh: "匹配ID或SKU的现有产品将被更新。不存在的产品将被跳过。" },
  "import.showAdvanced": { en: "Show advanced options", zh: "显示高级选项" },
  "import.hideAdvanced": { en: "Hide advanced options", zh: "隐藏高级选项" },
  "import.serverPath": { en: "Alternatively, enter the path to a CSV file on your server:", zh: "或者，输入服务器上CSV文件的路径：" },
  "import.delimiter": { en: "CSV Delimiter", zh: "CSV分隔符" },
  "import.usePrevious": { en: "Use previous column mapping preferences?", zh: "使用之前的字段映射偏好？" },
  "import.encoding": { en: "Character encoding of the file", zh: "文件字符编码" },
  "import.autodetect": { en: "Autodetect", zh: "自动检测" },
  "import.continue": { en: "Continue", zh: "继续" },
  "import.back": { en: "Back", zh: "返回" },
  "import.mapTitle": { en: "Map CSV fields to products", zh: "将CSV字段映射到产品" },
  "import.mapDesc": { en: "Select fields from your CSV file to map against products fields, or to ignore during import.", zh: "选择CSV文件中的字段映射到产品字段，或在导入时忽略。" },
  "import.columnName": { en: "Column name", zh: "列名" },
  "import.mapToField": { en: "Map to field", zh: "映射到字段" },
  "import.sample": { en: "Sample", zh: "示例" },
  "import.doNotImport": { en: "Do not import", zh: "不导入" },
  "import.runImport": { en: "Run the importer", zh: "运行导入器" },
  "import.importing": { en: "Importing", zh: "导入中" },
  "import.importingDesc": { en: "Your products are now being imported...", zh: "您的商品正在导入中..." },
  "import.complete": { en: "Import complete!", zh: "导入完成！" },
  "import.productsImported": { en: "products imported. File uploaded:", zh: "个商品已导入。上传的文件：" },
  "import.viewProducts": { en: "View products", zh: "查看商品" },
  "import.importAnother": { en: "Import another file", zh: "导入另一个文件" },

  // Discover / Nohi Database
  "discover.websites": { en: "Websites", zh: "网站" },
  "discover.websitesDesc": { en: "Browse and search websites in the Nohi product database.", zh: "浏览和搜索Nohi产品数据库中的网站。" },
  "discover.searchWebsites": { en: "Search websites...", zh: "搜索网站..." },
  "discover.random": { en: "Random", zh: "随机" },
  "discover.website": { en: "Website", zh: "网站" },
  "discover.title": { en: "Title", zh: "标题" },
  "discover.productsCount": { en: "Products", zh: "商品数" },
  "discover.brands": { en: "Brands", zh: "品牌" },
  "discover.brandsDesc": { en: "Browse brands in the Nohi product database.", zh: "浏览Nohi产品数据库中的品牌。" },
  "discover.searchBrands": { en: "Search brands...", zh: "搜索品牌..." },
  "discover.categories": { en: "Categories", zh: "品类" },
  "discover.categoriesDesc": { en: "Browse products by category.", zh: "按类别浏览产品。" },
  "discover.selectCategory": { en: "Select a category to view subcategories", zh: "选择一个类别查看子分类" },
  "discover.subcategories": { en: "Subcategories", zh: "子分类" },
  "discover.products": { en: "Products", zh: "商品" },
  "discover.productsDesc": { en: "Browse and add products to your catalog.", zh: "浏览并将商品添加到您的目录。" },
  "discover.searchProducts": { en: "Search products...", zh: "搜索商品..." },
  "discover.allCategories": { en: "All Categories", zh: "所有类别" },
  "discover.allBrands": { en: "All Brands", zh: "所有品牌" },
  "discover.priceRange": { en: "Price Range", zh: "价格区间" },
  "discover.any": { en: "Any", zh: "任意" },
  "discover.selected": { en: "selected", zh: "已选择" },
  "discover.addToCatalog": { en: "Add to Catalog", zh: "添加到目录" },
  "discover.addingToCatalog": { en: "Adding to Catalog...", zh: "正在添加到目录..." },

  // Product Detail
  "product.source": { en: "Source", zh: "来源" },
  "product.price": { en: "Price", zh: "价格" },
  "product.description": { en: "Description", zh: "描述" },
  "product.colors": { en: "Colors", zh: "颜色" },
  "product.materials": { en: "Materials", zh: "材质" },
  "product.categories": { en: "Categories", zh: "分类" },
  "product.keyFeatures": { en: "Key Features", zh: "主要特点" },
  "product.addToCatalog": { en: "Add to Catalog", zh: "添加到目录" },

  // ===== Brand Context =====
  "brandContext.title": { en: "Brand Context", zh: "品牌信息" },
  "brandContext.description": { en: "Configure how AI agents understand and represent your brand.", zh: "配置AI智能体如何理解和呈现您的品牌。" },
  "brandContext.details": { en: "Details", zh: "详情" },
  "brandContext.detailsDesc": { en: "Basic brand information and positioning.", zh: "基本品牌信息和定位。" },
  "brandContext.guardrails": { en: "Guardrails", zh: "品牌护栏" },
  "brandContext.guardrailsDesc": { en: "Set boundaries for AI interactions.", zh: "设置AI交互的边界。" },
  "brandContext.visualStyle": { en: "Visual Style", zh: "视觉风格" },
  "brandContext.visualStyleDesc": { en: "Brand colors, fonts, and visual identity.", zh: "品牌颜色、字体和视觉标识。" },
  "brandContext.brandStory": { en: "Brand Story", zh: "品牌故事" },
  "brandContext.brandStoryDesc": { en: "Your brand's narrative and values.", zh: "您的品牌叙事和价值观。" },
  "brandContext.postsUgc": { en: "Posts & UGC Assets", zh: "帖子与UGC素材" },
  "brandContext.postsUgcDesc": { en: "Social content and user-generated media.", zh: "社交内容和用户生成媒体。" },
  "brandContext.fulfillment": { en: "Fulfillment", zh: "履约配送" },
  "brandContext.fulfillmentDesc": { en: "Shipping and delivery information.", zh: "物流和配送信息。" },

  // Brand Details
  "details.title": { en: "Brand Details", zh: "品牌详情" },
  "details.description": { en: "Basic information about your brand that AI agents will use.", zh: "AI智能体将使用的品牌基本信息。" },
  "details.brandName": { en: "Brand Name", zh: "品牌名称" },
  "details.tagline": { en: "Tagline", zh: "标语" },
  "details.industry": { en: "Industry", zh: "行业" },
  "details.targetAudience": { en: "Target Audience", zh: "目标受众" },
  "details.pricePosition": { en: "Price Positioning", zh: "价格定位" },
  "details.budget": { en: "Budget", zh: "经济型" },
  "details.midRange": { en: "Mid-Range", zh: "中端" },
  "details.premium": { en: "Premium", zh: "高端" },
  "details.luxury": { en: "Luxury", zh: "奢侈品" },

  // Guardrails
  "guardrails.title": { en: "Guardrails", zh: "品牌护栏" },
  "guardrails.description": { en: "Set rules and boundaries for how AI agents represent your brand.", zh: "设置AI智能体如何呈现您品牌的规则和边界。" },
  "guardrails.neverMention": { en: "Never Mention", zh: "禁止提及" },
  "guardrails.neverMentionDesc": { en: "Topics or competitors the AI should never bring up.", zh: "AI永远不应提及的话题或竞争对手。" },
  "guardrails.alwaysInclude": { en: "Always Include", zh: "必须包含" },
  "guardrails.alwaysIncludeDesc": { en: "Key points the AI should always mention.", zh: "AI应始终提及的关键点。" },
  "guardrails.toneGuidelines": { en: "Tone Guidelines", zh: "语气指南" },
  "guardrails.toneGuidelinesDesc": { en: "How the AI should communicate.", zh: "AI应如何进行沟通。" },

  // Visual Style
  "visualStyle.title": { en: "Visual Style", zh: "视觉风格" },
  "visualStyle.description": { en: "Define your brand's visual identity for AI-generated content.", zh: "为AI生成的内容定义您的品牌视觉标识。" },
  "visualStyle.primaryColor": { en: "Primary Color", zh: "主色调" },
  "visualStyle.secondaryColor": { en: "Secondary Color", zh: "辅助色" },
  "visualStyle.logo": { en: "Logo", zh: "Logo" },
  "visualStyle.uploadLogo": { en: "Upload Logo", zh: "上传Logo" },
  "visualStyle.fontStyle": { en: "Font Style", zh: "字体风格" },
  "visualStyle.imageStyle": { en: "Image Style", zh: "图片风格" },

  // Brand Story
  "brandStory.title": { en: "Brand Story", zh: "品牌故事" },
  "brandStory.description": { en: "Share your brand's narrative and values.", zh: "分享您的品牌叙事和价值观。" },
  "brandStory.pageDesc": { en: "Your brand narrative helps agents understand your mission and communicate it to shoppers.", zh: "您的品牌叙事帮助智能体理解您的使命并传达给购物者。" },
  "brandStory.storyTitle": { en: "Brand Story", zh: "品牌故事" },
  "brandStory.storyDesc": { en: "A concise overview of your brand (recommended 150 words or fewer).", zh: "您的品牌简要概述（建议150字以内）。" },
  "brandStory.storyPlaceholder": { en: "Tell agents about your brand...", zh: "向智能体介绍您的品牌..." },
  "brandStory.founderNote": { en: "Founder Note", zh: "创始人寄语" },
  "brandStory.founderNoteDesc": { en: "A personal message from the founder that adds authenticity to your brand.", zh: "来自创始人的个人寄语，为您的品牌增添真实感。" },
  "brandStory.founderNotePlaceholder": { en: "Share a personal note from the founder...", zh: "分享创始人的个人寄语..." },
  "brandStory.origin": { en: "Origin Story", zh: "起源故事" },
  "brandStory.originDesc": { en: "How your brand started.", zh: "您的品牌是如何开始的。" },
  "brandStory.mission": { en: "Mission", zh: "使命" },
  "brandStory.missionDesc": { en: "What your brand aims to achieve.", zh: "您的品牌旨在实现什么。" },
  "brandStory.values": { en: "Core Values", zh: "核心价值观" },
  "brandStory.valuesDesc": { en: "The principles that guide your brand.", zh: "指导您品牌的原则。" },

  // Details
  "details.title": { en: "Details", zh: "详情" },
  "details.pageDesc": { en: "Define your brand positioning so AI agents can match you with the right shoppers.", zh: "定义您的品牌定位，让AI智能体能将您与合适的购物者匹配。" },
  "details.coreCategory": { en: "Core Category", zh: "核心品类" },
  "details.coreCategoryDesc": { en: "Select all categories that apply to your brand.", zh: "选择适用于您品牌的所有品类。" },
  "details.aovTier": { en: "AOV Tier", zh: "客单价区间" },
  "details.aovTierDesc": { en: "Average order value range for your products.", zh: "您产品的平均订单价值区间。" },
  "details.purchaseType": { en: "Purchase Type", zh: "购买类型" },
  "details.purchaseTypeDesc": { en: "How shoppers typically buy your products.", zh: "购物者通常如何购买您的产品。" },
  "details.primaryAudience": { en: "Primary Audience", zh: "主要受众" },
  "details.primaryAudienceDesc": { en: "Select audience segments or add your own.", zh: "选择受众群体或添加自定义。" },
  "details.audiencePlaceholder": { en: "Type a custom audience and press Enter...", zh: "输入自定义受众并按回车..." },
  "details.scenarioTags": { en: "Scenario Tags", zh: "场景标签" },
  "details.scenarioTagsDesc": { en: "Shopping scenarios where your products fit naturally.", zh: "您的产品自然适合的购物场景。" },
  "details.scenarioPlaceholder": { en: "Type a custom scenario and press Enter...", zh: "输入自定义场景并按回车..." },
  "details.intentTags": { en: "Intent Tags", zh: "意图标签" },
  "details.intentTagsDesc": { en: "Shopper intents that match your products.", zh: "与您产品匹配的购物者意图。" },
  "details.intentPlaceholder": { en: "Type a custom intent and press Enter...", zh: "输入自定义意图并按回车..." },

  // Guardrails
  "guardrails.title": { en: "Guardrails", zh: "品牌护栏" },
  "guardrails.pageDesc": { en: "Define restrictions so agents never associate your brand with unsuitable contexts.", zh: "定义限制规则，确保智能体不会将您的品牌与不适当的情境关联。" },
  "guardrails.excludedAudiences": { en: "Excluded Audiences", zh: "排除受众" },
  "guardrails.excludedAudiencesDesc": { en: "Audiences your products should never be recommended to.", zh: "您的产品不应被推荐给的受众群体。" },
  "guardrails.excludedPlaceholder": { en: "Type a custom exclusion and press Enter...", zh: "输入自定义排除项并按回车..." },
  "guardrails.prohibitedScenarios": { en: "Prohibited Scenarios", zh: "禁止场景" },
  "guardrails.prohibitedScenariosDesc": { en: "Use-cases where your products must not be suggested.", zh: "不得推荐您产品的使用场景。" },
  "guardrails.scenarioPlaceholder": { en: "Type a custom scenario and press Enter...", zh: "输入自定义场景并按回车..." },
  "guardrails.blockedKeywords": { en: "Blocked Keywords", zh: "屏蔽关键词" },
  "guardrails.blockedKeywordsDesc": { en: "Keywords that agents should never associate with your brand.", zh: "智能体不应与您品牌关联的关键词。" },
  "guardrails.keywordPlaceholder": { en: "Type a custom keyword and press Enter...", zh: "输入自定义关键词并按回车..." },

  // Visual Style
  "visualStyle.title": { en: "Visual Style", zh: "视觉风格" },
  "visualStyle.pageDesc": { en: "Style tags help agents understand your brand's visual identity and aesthetic.", zh: "风格标签帮助智能体理解您品牌的视觉标识和美学。" },
  "visualStyle.styleTags": { en: "Style Tags", zh: "风格标签" },
  "visualStyle.styleTagsDesc": { en: "Select tags that represent your brand aesthetic, or create custom ones.", zh: "选择代表您品牌美学的标签，或创建自定义标签。" },
  "visualStyle.placeholder": { en: "Type a custom style tag and press Enter...", zh: "输入自定义风格标签并按回车..." },
  "visualStyle.preview": { en: "Preview", zh: "预览" },
  "visualStyle.previewDesc": { en: "This is how agents will perceive your brand aesthetic.", zh: "这是智能体将如何感知您的品牌美学。" },
  "visualStyle.noTags": { en: "No style tags defined yet. Add tags above to define your visual identity.", zh: "尚未定义风格标签。在上方添加标签以定义您的视觉标识。" },

  // Posts & UGC
  "postsUgc.title": { en: "Posts & UGC Assets", zh: "帖子与UGC素材" },
  "postsUgc.pageDesc": { en: "Manage your brand content that agents surface to shoppers.", zh: "管理智能体向购物者展示的品牌内容。" },
  "postsUgc.description": { en: "Manage social content and user-generated media for AI agents.", zh: "管理AI智能体的社交内容和用户生成媒体。" },
  "postsUgc.uploadMedia": { en: "Upload Media", zh: "上传媒体" },
  "postsUgc.socialPosts": { en: "Social Posts", zh: "社交帖子" },
  "postsUgc.ugcContent": { en: "UGC Content", zh: "UGC内容" },
  "postsUgc.reviews": { en: "Customer Reviews", zh: "客户评价" },
  "postsUgc.nohiPosts": { en: "Nohi Posts", zh: "Nohi帖子" },
  "postsUgc.verifiedReviews": { en: "Verified Reviews", zh: "认证评价" },
  "postsUgc.brandMedia": { en: "Brand Media", zh: "品牌媒体" },
  "postsUgc.ugcAssets": { en: "UGC Assets", zh: "UGC素材" },
  "postsUgc.postsTotal": { en: "posts total", zh: "篇帖子" },
  "postsUgc.newPost": { en: "New Post", zh: "新建帖子" },
  "postsUgc.noPosts": { en: "No posts yet. Create your first post to engage agents.", zh: "暂无帖子。创建第一篇帖子来吸引智能体。" },
  "postsUgc.connectReviews": { en: "Connect reviews to Shopify", zh: "将评价连接到Shopify" },
  "postsUgc.connectReviewsDesc": { en: "Add verified reviews to your Shopify product metadata so agents can surface them to shoppers.", zh: "将认证评价添加到您的Shopify产品元数据中，以便智能体向购物者展示。" },
  "postsUgc.learnMore": { en: "Shopify's metafield documentation", zh: "Shopify元字段文档" },
  "postsUgc.verifiedReviewsCount": { en: "verified reviews from real customers.", zh: "条来自真实客户的认证评价。" },
  "postsUgc.verified": { en: "Verified", zh: "已认证" },
  "postsUgc.product": { en: "Product", zh: "产品" },
  "postsUgc.mediaAssets": { en: "media assets", zh: "个媒体素材" },
  "postsUgc.open": { en: "Open", zh: "打开" },
  "postsUgc.ugcCount": { en: "user-generated content pieces. Approve UGC to let agents reference it.", zh: "个用户生成内容。批准UGC后智能体可以引用。" },
  "postsUgc.approve": { en: "Approve", zh: "批准" },
  "postsUgc.approved": { en: "Approved", zh: "已批准" },
  "postsUgc.published": { en: "Published", zh: "已发布" },
  "postsUgc.scheduled": { en: "Scheduled", zh: "已计划" },
  "postsUgc.draft": { en: "Draft", zh: "草稿" },
  "postsUgc.createPost": { en: "Create Nohi Post", zh: "创建Nohi帖子" },
  "postsUgc.createPostDesc": { en: "Posts help agents understand your brand and surface content to shoppers.", zh: "帖子帮助智能体理解您的品牌并向购物者展示内容。" },
  "postsUgc.postTitle": { en: "Title", zh: "标题" },
  "postsUgc.postTitlePlaceholder": { en: "Post title...", zh: "帖子标题..." },
  "postsUgc.postContent": { en: "Content", zh: "内容" },
  "postsUgc.postContentPlaceholder": { en: "Write your post content...", zh: "撰写帖子内容..." },
  "postsUgc.imageUrl": { en: "Image URL (optional)", zh: "图片URL（可选）" },
  "postsUgc.tags": { en: "Tags", zh: "标签" },
  "postsUgc.addTags": { en: "Add tags...", zh: "添加标签..." },
  "postsUgc.createPostBtn": { en: "Create Post", zh: "创建帖子" },
  "postsUgc.uploadBrandMedia": { en: "Upload Brand Media", zh: "上传品牌媒体" },
  "postsUgc.uploadMediaDesc": { en: "Add images or videos that represent your brand.", zh: "添加代表您品牌的图片或视频。" },
  "postsUgc.type": { en: "Type", zh: "类型" },
  "postsUgc.image": { en: "Image", zh: "图片" },
  "postsUgc.video": { en: "Video", zh: "视频" },
  "postsUgc.fileName": { en: "File Name", zh: "文件名" },
  "postsUgc.fileNamePlaceholder": { en: "e.g. hero-spring-2026.jpg", zh: "例如 hero-spring-2026.jpg" },
  "postsUgc.caption": { en: "Caption", zh: "描述" },
  "postsUgc.captionPlaceholder": { en: "Describe this media...", zh: "描述这个媒体..." },
  "postsUgc.upload": { en: "Upload", zh: "上传" },

  // Fulfillment
  "fulfillment.title": { en: "Fulfillment", zh: "履约配送" },
  "fulfillment.description": { en: "Shipping and delivery information for AI agents.", zh: "AI智能体的物流和配送信息。" },
  "fulfillment.pageDesc": { en: "Default fulfillment settings applied to all listings. Product-level overrides can be set in Shopify meta fields.", zh: "应用于所有商品的默认履约设置。可在Shopify元字段中设置产品级别的覆盖。" },
  "fulfillment.shippingSla": { en: "Shipping SLA", zh: "物流SLA" },
  "fulfillment.shippingSlaDesc": { en: "Select your fulfillment tier based on your operational capacity.", zh: "根据您的运营能力选择履约等级。" },
  "fulfillment.platinum": { en: "Platinum", zh: "铂金" },
  "fulfillment.platinumDesc": { en: "1-2 business days processing, 99%+ on-time", zh: "1-2个工作日处理，99%+准时率" },
  "fulfillment.gold": { en: "Gold", zh: "黄金" },
  "fulfillment.goldDesc": { en: "2-3 business days processing, 97%+ on-time", zh: "2-3个工作日处理，97%+准时率" },
  "fulfillment.silver": { en: "Silver", zh: "白银" },
  "fulfillment.silverDesc": { en: "3-5 business days processing, 95%+ on-time", zh: "3-5个工作日处理，95%+准时率" },
  "fulfillment.standard": { en: "Standard", zh: "标准" },
  "fulfillment.standardDesc": { en: "5-7 business days processing, 90%+ on-time", zh: "5-7个工作日处理，90%+准时率" },
  "fulfillment.processingTime": { en: "Processing Time", zh: "处理时间" },
  "fulfillment.onTimeRate": { en: "On-time Rate", zh: "准时率" },
  "fulfillment.returnRate": { en: "Return Rate", zh: "退货率" },
  "fulfillment.damageRate": { en: "Damage Rate", zh: "损坏率" },
  "fulfillment.days": { en: "days", zh: "天" },
  "fulfillment.businessDays": { en: "business days", zh: "个工作日" },
  "fulfillment.refundTime": { en: "Refund Time", zh: "退款时间" },
  "fulfillment.refundTimeDesc": { en: "Average business days to process a refund.", zh: "处理退款的平均工作日。" },
  "fulfillment.returnPolicy": { en: "Return Policy", zh: "退换政策" },
  "fulfillment.returnPolicyDesc": { en: "Your default return policy for all listings.", zh: "您所有商品的默认退换政策。" },
  "fulfillment.returnPolicyPlaceholder": { en: "Describe your return policy...", zh: "描述您的退换政策..." },
  "fulfillment.note": { en: "Product-level fulfillment settings can be configured via Shopify meta fields. These defaults apply to all listings without product-specific overrides.", zh: "产品级别的履约设置可通过Shopify元字段配置。这些默认设置适用于所有没有产品特定覆盖的商品。" },
  "fulfillment.shippingPolicy": { en: "Shipping Policy", zh: "配送政策" },
  "fulfillment.deliveryTime": { en: "Delivery Time", zh: "配送时间" },
  "fulfillment.shippingRegions": { en: "Shipping Regions", zh: "配送区域" },

  // ===== Analytics =====
  "analytics.title": { en: "Analytics", zh: "数据分析" },
  "analytics.description": { en: "Track your performance across AI shopping channels.", zh: "追踪您在AI购物渠道的表现。" },
  "analytics.overview": { en: "Overview", zh: "概览" },
  "analytics.revenue": { en: "Revenue", zh: "收入" },
  "analytics.impressions": { en: "Impressions", zh: "曝光量" },
  "analytics.clicks": { en: "Clicks", zh: "点击量" },
  "analytics.conversions": { en: "Conversions", zh: "转化量" },
  "analytics.conversionRate": { en: "Conversion Rate", zh: "转化率" },
  "analytics.topProducts": { en: "Top Products", zh: "热门商品" },
  "analytics.topChannels": { en: "Top Channels", zh: "热门渠道" },
  "analytics.timeRange": { en: "Time Range", zh: "时间范围" },
  "analytics.last7Days": { en: "Last 7 days", zh: "最近7天" },
  "analytics.last30Days": { en: "Last 30 days", zh: "最近30天" },
  "analytics.last90Days": { en: "Last 90 days", zh: "最近90天" },
  "analytics.custom": { en: "Custom", zh: "自定义" },

  // ===== Common =====
  "common.demo": { en: "Nohi Demo Store", zh: "Nohi演示店铺" },
  "common.freePlan": { en: "Free Plan", zh: "免费版" },
  "common.save": { en: "Save", zh: "保存" },
  "common.cancel": { en: "Cancel", zh: "取消" },
  "common.edit": { en: "Edit", zh: "编辑" },
  "common.delete": { en: "Delete", zh: "删除" },
  "common.add": { en: "Add", zh: "添加" },
  "common.search": { en: "Search", zh: "搜索" },
  "common.filter": { en: "Filter", zh: "筛选" },
  "common.sort": { en: "Sort", zh: "排序" },
  "common.loading": { en: "Loading...", zh: "加载中..." },
  "common.noResults": { en: "No results found", zh: "未找到结果" },
  "common.viewAll": { en: "View All", zh: "查看全部" },
  "common.learnMore": { en: "Learn more", zh: "了解更多" },
  "common.comingSoon": { en: "Coming Soon", zh: "即将推出" },
  "common.request": { en: "Request", zh: "请求" },
  "common.requestSent": { en: "Request sent", zh: "已发送请求" },
  "common.expires": { en: "Expires", zh: "有效期" },
  "common.words": { en: "words", zh: "字" },
  "common.saveChanges": { en: "Save Changes", zh: "保存更改" },
  "common.recommended": { en: "Recommended", zh: "推荐" },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    // Load saved language from localStorage
    const saved = localStorage.getItem("nohi-language") as Language
    if (saved && (saved === "en" || saved === "zh")) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("nohi-language", lang)
  }

  const t = (key: string): string => {
    const translation = translations[key]
    if (!translation) {
      // Return the key without warning in production
      return key
    }
    return translation[language] || translation.en || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
